# Generated by Django 2.2.6 on 2020-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='group_follows', to='account.Profile'),
        ),
    ]
