# Generated by Django 2.2.6 on 2020-12-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='likes',
        ),
    ]
