# Generated by Django 2.2.6 on 2020-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('group', '0003_remove_group_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='group_post_likes', to='account.Profile'),
        ),
    ]
