# Generated by Django 2.2.6 on 2020-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('page', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='page_post_comment_likes', to='account.Profile'),
        ),
    ]
